version: '3'
networks:
  net:
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - net
    ports:
      - 15672:15672
      - 5672:5672
  eureka:
    image: "steeltoeoss/eurekaserver"
    container_name: eurekaserver
    networks:
      - net
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/eureka/apps/ && echo 'OK'"]
      interval: 10s
      timeout: 5s
      retries: 3
  metworkinguser:
    image: metworkinguser
    container_name: metworkinguser-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - net
    depends_on:
      eureka:
        condition: service_healthy 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./src/dbmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - net